import type { SkripsiPresetV1 } from "@/types/preset";

export const DEFAULT_PRESET: SkripsiPresetV1 = {
  id: "skripsi-umum-id-v1",
  name: "Skripsi Umum Indonesia",
  version: "1.0.0",
  locale: "id-ID",
  styles: {
    body: {
      text: {
        fontName: "Times New Roman",
        fontSizePt: 12,
        bold: false,
        italic: false,
        underline: "None",
        allCaps: false,
      },
      paragraph: {
        alignment: "Justified",
        lineSpacingPt: 24,
        spaceBeforePt: 0,
        spaceAfterPt: 0,
        firstLineIndentCm: 1.27,
        leftIndentCm: 0,
        rightIndentCm: 0,
      },
    },
    heading1: {
      text: {
        fontName: "Times New Roman",
        fontSizePt: 14,
        bold: true,
        italic: false,
        underline: "None",
        allCaps: true,
      },
      paragraph: {
        alignment: "Centered",
        lineSpacingPt: 24,
        spaceBeforePt: 12,
        spaceAfterPt: 12,
        firstLineIndentCm: 0,
        leftIndentCm: 0,
        rightIndentCm: 0,
      },
    },
    heading2: {
      text: {
        fontName: "Times New Roman",
        fontSizePt: 12,
        bold: true,
        italic: false,
        underline: "None",
        allCaps: false,
      },
      paragraph: {
        alignment: "Left",
        lineSpacingPt: 24,
        spaceBeforePt: 12,
        spaceAfterPt: 6,
        firstLineIndentCm: 0,
        leftIndentCm: 0,
        rightIndentCm: 0,
      },
    },
    heading3: {
      text: {
        fontName: "Times New Roman",
        fontSizePt: 12,
        bold: true,
        italic: true,
        underline: "None",
        allCaps: false,
      },
      paragraph: {
        alignment: "Left",
        lineSpacingPt: 24,
        spaceBeforePt: 6,
        spaceAfterPt: 6,
        firstLineIndentCm: 0,
        leftIndentCm: 0,
        rightIndentCm: 0,
      },
    },
    quote: {
      text: {
        fontName: "Times New Roman",
        fontSizePt: 11,
        bold: false,
        italic: true,
        underline: "None",
        allCaps: false,
      },
      paragraph: {
        alignment: "Justified",
        lineSpacingPt: 20,
        spaceBeforePt: 6,
        spaceAfterPt: 6,
        firstLineIndentCm: 0,
        leftIndentCm: 1.27,
        rightIndentCm: 1.27,
      },
    },
    captionFigure: {
      text: {
        fontName: "Times New Roman",
        fontSizePt: 11,
        bold: false,
        italic: false,
        underline: "None",
        allCaps: false,
      },
      paragraph: {
        alignment: "Centered",
        lineSpacingPt: 16,
        spaceBeforePt: 6,
        spaceAfterPt: 6,
        firstLineIndentCm: 0,
        leftIndentCm: 0,
        rightIndentCm: 0,
      },
    },
    captionTable: {
      text: {
        fontName: "Times New Roman",
        fontSizePt: 11,
        bold: false,
        italic: false,
        underline: "None",
        allCaps: false,
      },
      paragraph: {
        alignment: "Centered",
        lineSpacingPt: 16,
        spaceBeforePt: 6,
        spaceAfterPt: 6,
        firstLineIndentCm: 0,
        leftIndentCm: 0,
        rightIndentCm: 0,
      },
    },
  },
  captions: {
    figure: {
      label: "Figure",
      separator: ".",
      titleCase: "Sentence",
    },
    table: {
      label: "Table",
      separator: ".",
      titleCase: "Sentence",
    },
  },
};
